config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :kittens
  root "kittens#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
  validates :name, :age, :cuteness, :softness, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  before_action :set_kitten, only: %i[ show edit update destroy ]

  def index
    @kittens = Kitten.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :index, status: :ok }
    end
  end

  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :show, status: :ok }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def edit
  end

  def create
    @kitten = Kitten.new(kitten_params)
  end

  def update
  end

  def destroy
    @kitten.destroy
  end

  private
    def set_kitten
      @kitten = Kitten.find(params[:id])
    end

    def kitten_params
      params.require(:kitten).permit(:name, :age, :cuteness, :softness)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_with(model: kitten) do |form| %>
  <% if kitten.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(kitten.errors.count, "error") %> prohibited this kitten from being saved:</h2>

      <ul>
        <% kitten.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :cuteness %>
    <%= form.text_field :cuteness %>
  </div>

  <div class="field">
    <%= form.label :softness %>
    <%= form.text_field :softness %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/kittens/edit.html.erb
<h1>Editing kitten</h1>

<%= render 'form', kitten: @kitten %>

<%= link_to 'Show', @kitten %> |
<%= link_to 'Back', kittens_path %>

app/views/kittens/index.html.erb
<h1>Kittens</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Cuteness</th>
      <th>Softness</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @kittens.each do |kitten| %>
      <tr>
        <td><%= kitten.name %></td>
        <td><%= kitten.age %></td>
        <td><%= kitten.cuteness %></td>
        <td><%= kitten.softness %></td>
        <td><%= link_to 'Show', kitten %></td>
        <td><%= link_to 'Edit', edit_kitten_path(kitten) %></td>
        <td><%= link_to 'Destroy', kitten, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Kitten', new_kitten_path %>

app/views/kittens/new.html.erb
<h1>New Kitten</h1>

<%= render 'form', kitten: @kitten %>

<%= link_to 'Back', kittens_path %>

app/views/kittens/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @kitten.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @kitten.age %>
</p>

<p>
  <strong>Cuteness:</strong>
  <%= @kitten.cuteness %>
</p>

<p>
  <strong>Softness:</strong>
  <%= @kitten.softness %>
</p>

<%= link_to 'Edit', edit_kitten_path(@kitten) %> |
<%= link_to 'Destroy', @kitten, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', kittens_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div>
        <p class="alert alert-success"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div>
        <p class="alert alert-danger"><%= alert %></p>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>